test:
  adapter: postgresql
  encoding: utf8
  database: {{ canvas_database.test }}
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: {{ canvas_database.development }}
  timeout: 5000
  queue:
    adapter: postgresql
    encoding: utf8
    database: {{ canvas_queue_database.development }}
    timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: {{ canvas_database.production }}
  host: localhost
  username: {{ canvas_db_user }}
  password: {{ canvas_db_password }}
  timeout: 5000
  queue:
    adapter: postgresql
    encoding: utf8
    database: {{ canvas_queue_database.production }}
    host: localhost
    username: {{ canvas_db_user }}
    password: {{ canvas_db_password }}
    timeout: 5000
