# db.yml
#   PostgreSQL setup
#
# Created 2015-03-26 daveadams@gmail.com
#
# This software is public domain.
#

- name: Database Server Setup
  hosts: db
  sudo: yes
  vars:
    postgres_etc_dir: /etc/postgresql/9.3/main
    postgres_conf: "{{ postgres_etc_dir }}/postgresql.conf"
    postgres_hba_conf: "{{ postgres_etc_dir }}/pg_hba.conf"
    canvas_production_databases:
      - canvas_production
      - canvas_queue_production
  tasks:
    - name: Install Postgresql
      apt: name=postgresql-9.3

    - name: Install python libraries required to manage postgresql with Ansible
      apt: name=python-psycopg2

    - name: Create Canvas DB user
      postgresql_user: name={{ canvas_db_user }} password={{ canvas_db_password }}
      sudo_user: postgres

    - name: Create Canvas databases
      postgresql_db: name={{ item }} owner={{ canvas_db_user }}
      sudo_user: postgres
      with_items: canvas_production_databases

    - name: Listen on private network
      lineinfile: dest={{ postgres_conf }} line="listen_addresses = '{{ host_settings[ansible_hostname].private_ip }}'" regexp=^listen_addresses
      notify: reload postgresql

    - name: Allow canvas user to connect remotely
      lineinfile: dest={{ postgres_hba_conf }} insertbefore="^# DO NOT DISABLE!$" line="host {{ item }} canvas 192.168.100.0/24 md5"
      with_items: canvas_production_databases
      notify: reload postgresql

  handlers:
    - name: reload postgresql
      command: service postgresql reload
